# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DartCI

on:
  push:
    branches: [ master, develope ]
  pull_request:
    branches: [ master, develope ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
        
    - name: Install dependencies
      run: flutter pub get
    - name: Format code
      run: flutter format --set-exit-if-changed .
    - name: Static analysis
      run: flutter analyze
    - name: Flutter tests
      run: flutter test
    - name: Flutter build Android
      run: flutter build apk
    - name: Flutter tests
      run: flutter build ios --release --no-codesign

